global using NUnit.Framework;
global using RestSharp;
global using JsonSchema = NJsonSchema.JsonSchema;
global using TechTalk.SpecFlow;
global using Newtonsoft.Json.Linq;
global using System.Text.Json;
global using System.Collections.Generic;
global using AventStack.ExtentReports;
global using AventStack.ExtentReports.Reporter;
global using AventStack.ExtentReports.Gherkin.Model;
global using TechTalk.SpecFlow.CommonModels;
global using Elabor8_PracticeTest_Arjun.Libraries;